import Sidebar from '@/components/Sidebar'
import Head from 'next/head'
import Image from 'next/image'
// import { Inter } from 'next/font/google'

// const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
   <div>
    <Head>
      <title>Twitter Clone</title>
      <meta name="description" content="Generated by Nextjs"></meta>
      <link rel='stylesheet' href='/favicon.ico'></link>
    </Head>

    <main className='flex min-h-screen mx-auto'>
      {/* Sidebar */}
      <Sidebar/>

      {/* Feed */}

      {/* Widgets */}

      {/* Modal */}
    </main>
   </div>
  )
}
